Repository SDFIdk/FIRE, pull requests merged in 2025-04, with the labels that each got.

#820 Fix diverse små bugs
  fire/cli/niv/_regn.py
  fire/cli/niv/punktsamling.py
Labels: bug, backport 1.8

#822 fire niv ilæg-revision: Præciser dokumentation
  fire/cli/niv/_ilæg_revision.py
Labels: backport 1.8

#791 Udvid fire info sag med mere fleksibel søgefunktionalitet
  fire/api/firedb/hent.py
  fire/api/model/sagstyper.py
  fire/cli/info.py
Labels: ny funktionalitet
